'use strict';

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('mgm', {
  getGPUInfo: () => ipcRenderer.invoke('get-gpu-info'),
  getConfig: () => ipcRenderer.invoke('get-config'),
  saveConfig: (config) => ipcRenderer.invoke('save-config', config),
  createRestorePoint: () => ipcRenderer.invoke('create-restore-point'),
  setAutostart: (enabled) => ipcRenderer.invoke('set-autostart', enabled),
  applyMode: (config) => ipcRenderer.invoke('apply-mode', config),
  revertMode: () => ipcRenderer.invoke('revert-mode'),
  windowClose: () => ipcRenderer.send('window-close'),
  windowMinimize: () => ipcRenderer.send('window-minimize'),
  onTrayToggle: (cb) => ipcRenderer.on('tray-toggle-mode', (e, val) => cb(val)),
  metricsStart: () => ipcRenderer.send('metrics-start'),
  metricsStop: () => ipcRenderer.send('metrics-stop'),
  getMetricsSnapshot: () => ipcRenderer.invoke('get-metrics-snapshot'),
  getPingSnapshot: () => ipcRenderer.invoke('get-ping-snapshot'),
  pingStart: () => ipcRenderer.send('ping-start'),
  pingStop: () => ipcRenderer.send('ping-stop'),
  onPingData: (cb) => ipcRenderer.on('ping-data', (e, data) => cb(data)),
  exportCustomRules: (jsonContent) => ipcRenderer.invoke('export-custom-rules', jsonContent),
  importCustomRules: () => ipcRenderer.invoke('import-custom-rules'),
  onMetricsData: (cb) => ipcRenderer.on('metrics-data', (e, data) => cb(data)),
  onUpdaterStatus: (cb) => ipcRenderer.on('updater-status', (e, data) => cb(data)),
  onTrayPresetSwitch: (cb) => ipcRenderer.on('tray-switch-preset', (e, preset) => cb(preset)),
  notifyPresetChanged: (preset) => ipcRenderer.send('preset-changed', preset),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  downloadUpdate: () => ipcRenderer.invoke('download-update'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  getVersion: () => ipcRenderer.invoke('get-version'),
  getWhatsNew: () => ipcRenderer.invoke('get-whats-new'),
  minimizeToTray: () => ipcRenderer.send('window-minimize'),
  setNotifPrefs: (prefs) => ipcRenderer.send('set-notif-prefs', prefs),
  setMiniMode: (enabled) => ipcRenderer.send('set-mini-mode', enabled),
  setBarMode: (enabled) => ipcRenderer.send('set-bar-mode', enabled),
  setWindowOpacity: (value) => ipcRenderer.send('set-window-opacity', value),
  getStartupApps: () => ipcRenderer.invoke('get-startup-apps'),
  toggleStartupApp: (name, location, enable) => ipcRenderer.invoke('toggle-startup-app', name, location, enable)
});
